apiVersion: v1
kind: Service
metadata:
  labels:
    app: blue-svc
  name: blue-svc
spec:
  type: LoadBalancer
  selector:
    app: blue
  ports:
    - protocol: TCP
      port: 80
      targetPort: 80
