apiVersion: v1
kind: Service
metadata:
  labels:
    app: green-svc
  name: green-svc
spec:
  type: LoadBalancer
  selector:
    app: green
  ports:
    - protocol: TCP
      port: 80
      targetPort: 80
